In [4]:
import numpy as np
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.empty(())

array(1.)

In [11]:
np.empty((7,7))

array([[       nan, 4.941e-324, 4.387e-321, 1.976e-323, 4.862e-321,
        2.031e-321, 3.893e-321],
       [2.031e-321, 5.099e-321, 2.031e-321, 5.158e-321, 2.031e-321,
        5.237e-321, 2.031e-321],
       [7.707e-322, 2.031e-321, 2.628e-321, 2.031e-321, 2.549e-321,
        2.031e-321, 4.051e-321],
       [2.031e-321, 4.387e-321, 2.031e-321, 4.387e-321, 1.976e-323,
        0.000e+000, 0.000e+000],
       [0.000e+000, 0.000e+000, 0.000e+000, 0.000e+000, 0.000e+000,
        0.000e+000, 0.000e+000],
       [0.000e+000, 0.000e+000, 0.000e+000, 0.000e+000, 0.000e+000,
        0.000e+000, 0.000e+000],
       [0.000e+000, 0.000e+000, 0.000e+000, 0.000e+000, 0.000e+000,
        0.000e+000, 0.000e+000]])

In [12]:
lists = [1,2,3,4]
np.array((lists))

array([1, 2, 3, 4])

In [13]:
np.arange((1,100,10))

TypeError: arange: scalar arguments expected instead of a tuple.

In [14]:
np.arange(1,100,10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [16]:
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [18]:
x=np.arange(1,100,10)

In [19]:
x

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [20]:
x.shape

(10,)

In [29]:
x=np.zeros((10,10))

In [22]:
x.shape

(10, 10)

In [23]:
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [24]:
y=x.reshape((2,2,5,5))

In [25]:
y

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [27]:
#type of array
y.dtype

dtype('float64')

In [28]:
y.ndim

4

In [30]:
x.dtype

dtype('float64')

In [31]:
x.ndim

2