In [7]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])

In [3]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [10]:
a=np.random.randn(10)

In [11]:
b=np.random.randn(10)

In [12]:
a+b

array([-0.34120185,  0.21959968, -1.19835206, -0.47629118,  0.55871029,
        1.33167208,  0.40805184, -1.33322609,  1.41430948, -0.78619804])

In [13]:
a

array([-1.49521532, -0.18134012, -0.9670767 , -1.12429947,  0.6675074 ,
        1.9195253 ,  1.15855005, -1.0394084 ,  0.38807678,  0.00531272])

In [14]:
b

array([ 1.15401347,  0.4009398 , -0.23127536,  0.64800829, -0.1087971 ,
       -0.58785323, -0.75049821, -0.29381769,  1.0262327 , -0.79151075])

In [15]:
a*a


array([2.23566886e+00, 3.28842392e-02, 9.35237352e-01, 1.26404930e+00,
       4.45566125e-01, 3.68457738e+00, 1.34223821e+00, 1.08036982e+00,
       1.50603588e-01, 2.82249812e-05])

In [16]:
a>0

array([False, False, False, False,  True,  True,  True, False,  True,
        True])

In [17]:
a[a>0]

array([0.6675074 , 1.9195253 , 1.15855005, 0.38807678, 0.00531272])